### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by jacobrs** [SCS-Concordia/Website#5]
Add support for python3 since the current code doesn't seem to run when using the Python3 bin. The following error message is obtained:

```
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 14, in <module>
    import django
ImportError: No module named 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 17, in <module>
    "Couldn't import Django. Are you sure it's installed and "
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
```

**Comment by tamarindd** [comment]
It works with python3, I just tested it. Did you install django with pip3?

**Comment by jacobrs** [comment]
Nope. Should I run it with Python3 though?
